# Generated by Django 5.2.1 on 2025-07-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="image_url",
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="event_images/"),
        ),
    ]
