# Generated by Django 5.2.1 on 2025-09-13 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tran_id",
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
