# Generated by Django 5.2.1 on 2025-09-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_order_tran_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("due", "Due")], default="due", max_length=10
            ),
        ),
    ]
