# Generated by Django 5.2.1 on 2025-09-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("paid", "Paid"), ("due", "Due")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
